name: CI for MCDR

on:
  push:
    paths:
      - ".github/**"
      - "mcdreforged/**"
      - "tests/**"
      - "*.py"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  assemble:
    needs: test
    uses: ./.github/workflows/assemble.yml

  pypi-upload:
    runs-on: ubuntu-latest
    name: Make and upload a package to (Test)PyPI
    needs: test
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install setuptools wheel

    - name: Create distribution
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish distribution to TestPyPI
      if: github.event_name == 'push'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - uses: actions/upload-artifact@v3
      with:
        name: MCDReforged package distribution for ${{ github.sha }}
        path: dist/
